// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core';

export {};

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppBarDarkModeButton: typeof import('./components/appbar/AppBarDarkModeButton.vue')['default'];
    AppBarLangButton: typeof import('./components/appbar/AppBarLangButton.vue')['default'];
    MarkerInfo: typeof import('./components/new-map/MarkerInfo.vue')['default'];
    MarkerInfoCard: typeof import('./components/new-map/MarkerInfoCard.vue')['default'];
    NewMap: typeof import('./components/new-map/NewMap.vue')['default'];
    NewMapMenu: typeof import('./components/new-map/NewMapMenu.vue')['default'];
    NewMapMenuContent: typeof import('./components/new-map/NewMapMenuContent.vue')['default'];
    NewMapMenuDragWrapper: typeof import('./components/new-map/NewMapMenuDragWrapper.vue')['default'];
    RouterLink: typeof import('vue-router')['RouterLink'];
    RouterView: typeof import('vue-router')['RouterView'];
  }
}
